#!/bin/sh /etc/rc.common

START=96
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/lib/easymanet/status-cache.sh
    procd_set_param env EASYMANET_STATUS_CACHE_LOG=/var/log/easymanet-status-cache.log
    procd_set_param respawn 10 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
